Portfolio
sheldonwafula/portfolio pull request #1
Opened 2022-12-02 17:47 UTC by sheldonwafula

I have finished my project and all changes are complete.

2022-12-02 19:09 UTC, brainconnect93 requested changes
### Hi @sheldonwafula, 👋 

# STATUS: Changes Required :recycle:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/8btL6MtOii4AAAAM/very-close-wolfey.gif">

### To Highlight :1st_place_medal: 
-  Has a proper Pull Request. ✔️  
- No Linter errors :heavy_check_mark: 
- Good use of Github flow ✔️ 

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 19:09 UTC, brainconnect93 commented on index.css
> +
- [ ] You have made a great effort styling your project, but I would advise we stick to the Figma template in styling it as this is part of the project requirement. I will be highlighting some points that I would like you to make changes to.

Here is what you have in your design now 👇 

![sel](https://user-images.githubusercontent.com/78634841/205366024-f365c217-37a9-4f26-a541-5e17ff06439c.png)

And this is the Figma design 👇 

![real](https://user-images.githubusercontent.com/78634841/205366149-1968e5fa-b4b9-469b-95f6-9f17179d76af.png)

1. Kindly check the alignment of the header title with the description body. kindly compare your design to the Figma template
2. the space between the header to the description section is too much, kindly fix it.
3. Kindly check the `font size` and `font weight`.
4. Kindly check on the background image too as what you have in your design is quite different from what we have in the Figma template.

2022-12-02 19:09 UTC, brainconnect93 commented on README.md
> +
- [ ] Kindly add the table of content of the readme file template as this will showcase the contents you have in your readme and can help people to navigate around the document

2022-12-02 19:09 UTC, brainconnect93 commented on README.md
> +Feel free to check the [issues page](../../issues/).
- [ ] Kindly add the issue link to the readme file so that people can easily leave a message or open an issue via the link

2022-12-02 22:35 UTC, bienvenuushindi requested changes
### Hi @sheldonwafula ,

Good job implementing most of the required changes!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔
- Nice Design. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below.


**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-12-02 22:35 UTC, bienvenuushindi commented on index.css
> +  top: 63px;
:red_circle: As requested by the previous reviewer kindly make sure you reduce the top margin to match the figma design. The Logo and the navbar should have equal room at the top
Your Design
![top](https://user-images.githubusercontent.com/26736582/205399501-92667a68-8745-4969-89e7-ac60560fc404.png)

Figma Design
<img src="https://github.com/microverseinc/curriculum-html-css/raw/main/portfolio/images/m1_setup/toolbar-mobile.png">

I think if you use flexbox to design this section It will be easier to design. You can for example set display flex to the header section.

```
header {
    display: flex;
   justify-content: space-between
}
```

2022-12-02 22:35 UTC, bienvenuushindi commented on index.css
> +  position: absolute;
:red_circle:  Kindly reduce  the space between the header to the description section. You can remove this property ( `position:absolute`) and add some margin-top to this section 
Your deisgn
![space](https://user-images.githubusercontent.com/26736582/205400535-c979e8f6-1620-494d-980d-4c787d58dc2b.png)

2022-12-02 22:35 UTC, bienvenuushindi commented on index.css
> +  left: 24px;
:red_circle: Kindly reduce this value to make sure both the toolbar and the headline start at the line as it is on the Figma Design

Your Design
![alin](https://user-images.githubusercontent.com/26736582/205401251-fc2a98ba-b149-485c-bf72-65beb18e4705.png)

2022-12-03 07:48 UTC, Kossi-stack approved these changes
## Status: Approved ✔️
**Hi @sheldonwafula,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 🎉

![](https://user-images.githubusercontent.com/74506933/148243736-d9f63735-4cb1-411f-be28-34972618852d.gif)
You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

<img width="501" alt="Screenshot 2022-12-02 at 23 37 26" src="https://user-images.githubusercontent.com/81444338/205430660-82d9596c-9a19-4a15-94ed-8969e2a4601f.png">


## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-12-03 08:12 UTC, merged